server:
  port: 8981

spring:
  datasource:
    url: jdbc:mysql://192.168.0.99:3307/mobile-pay?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1hbl#QThztwcs
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-conn-lifetime-millis: 10000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
